<a href="https://colab.research.google.com/github/practice-grounds-wpaarth24/Neural_Network_Regression/blob/main/Tensor_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

random = tf.random.Generator.from_seed(30)
random_normal = random.normal(shape=(4, 4))
print(random_normal)
random_normal.ndim

tf.Tensor(
[[ 0.8357487   0.20849545  1.4040176  -2.7352831 ]
 [ 1.223223   -1.8653691   0.00511209 -1.0493752 ]
 [ 0.7901182   1.585549    0.4356279   0.23645182]
 [-0.15898712  1.302304    0.959224    0.85874265]], shape=(4, 4), dtype=float32)


2

In [ ]:
matrix = tf.constant([[10,5],
                      [3,4],
                      [8,10]])


In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(matrix, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  5],
       [ 3,  4],
       [ 8, 10]], dtype=int32)>

In [ ]:
A = tf.random.Generator.from_seed(42)
A = A.uniform(shape=[3,4,4,4])
A[2]

<tf.Tensor: shape=(4, 4, 4), dtype=float32, numpy=
array([[[0.23609889, 0.56451845, 0.44649565, 0.41026497],
        [0.60833323, 0.50973356, 0.31043375, 0.07893777],
        [0.57783425, 0.16236854, 0.63097   , 0.7254863 ],
        [0.8393048 , 0.89883757, 0.64980876, 0.0960505 ]],

       [[0.06560767, 0.6030959 , 0.5261806 , 0.29263592],
        [0.36828172, 0.9125351 , 0.9311757 , 0.80997777],
        [0.88897777, 0.38208318, 0.46514285, 0.26686597],
        [0.57392883, 0.9305825 , 0.97072124, 0.264992  ]],

       [[0.48514366, 0.64945745, 0.08074284, 0.03533149],
        [0.66343594, 0.5920874 , 0.89842534, 0.45204258],
        [0.05900347, 0.54448843, 0.06236184, 0.00481558],
        [0.0548979 , 0.30745876, 0.08170903, 0.05909014]],

       [[0.6011734 , 0.42620623, 0.3024857 , 0.7693486 ],
        [0.56310844, 0.00256145, 0.94034374, 0.30628622],
        [0.40648186, 0.89660215, 0.9323058 , 0.01358628],
        [0.7463044 , 0.3287711 , 0.89990544, 0.80902195]]], dtype=float32

In [ ]:
A[:2,:1,:4,:4]

<tf.Tensor: shape=(2, 1, 4, 4), dtype=float32, numpy=
array([[[[0.7493447 , 0.73561966, 0.45230794, 0.49039817],
         [0.1889317 , 0.52027524, 0.8736881 , 0.46921718],
         [0.63932586, 0.6467117 , 0.96246755, 0.41009164],
         [0.86540747, 0.8862978 , 0.27795732, 0.8857763 ]]],


       [[[0.18828917, 0.6658715 , 0.6190208 , 0.04422736],
         [0.49626625, 0.6474861 , 0.3557682 , 0.32033885],
         [0.33705008, 0.7391062 , 0.16512096, 0.41555858],
         [0.78638244, 0.45899415, 0.42686343, 0.5630441 ]]]],
      dtype=float32)>

In [ ]:
tf.size(A[0]).numpy()

64

In [ ]:
A1 = tf.random.Generator.from_seed(42)
A1 = A1.normal(shape=[2,2])
A1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
tf.expand_dims(A1, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]]], dtype=float32)>

In [ ]:
t1 = tf.constant([[10,7], [7,10], [8,15]])
t1 + 11
t2 = tf.constant([[10,7], [8,15],[7,10]])

In [ ]:
t1.shape, t2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
tf.math.add(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 14],
       [15, 25],
       [15, 25]], dtype=int32)>

In [ ]:
#tf.reshape(t2, shape=[3,2])

In [ ]:
t1,tf.transpose(t1)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10],
        [ 8, 15]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  8],
        [ 7, 10, 15]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(t1),t2)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[212, 255],
       [255, 349]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(t1),t2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[212, 255],
       [255, 349]], dtype=int32)>

In [ ]:
#Changing dtype
B = tf.constant([1.7,4.1])
B.dtype

tf.float32

In [ ]:
B = tf.cast(B, dtype = tf.float16)
B.dtype

tf.float16

# **Aggregation**
tf.abs(X) converts -ve values in a tensor to positive
*   Maximum:
*   Minimum:
*   Mean:
*   Sum:
*   Std Dev
*   Variance

In [ ]:
import numpy as np
D = tf.constant(np.random.randint(0,100,size=50))
D = tf.cast(D, dtype=tf.float32)

In [ ]:
print("Maximum is: ",tf.reduce_max(D))
print("Minimum is: ",tf.reduce_min(D))
print("Mean is: ", tf.reduce_mean(D))
print("Sum is: ", tf.reduce_sum(D))
import tensorflow_probability as tfp
print("Variance is: ",tfp.stats.variance(D))

Maximum is:  tf.Tensor(98.0, shape=(), dtype=float32)
Minimum is:  tf.Tensor(3.0, shape=(), dtype=float32)
Mean is:  tf.Tensor(49.62, shape=(), dtype=float32)
Sum is:  tf.Tensor(2481.0, shape=(), dtype=float32)
Variance is:  tf.Tensor(841.0756, shape=(), dtype=float32)


In [ ]:
#Wont work unless dytpe if float32
print("Standard Deviation is: ", tf.math.reduce_std(tf.cast(D,dtype = tf.float32)))
print("Variance is: ", tf.math.reduce_variance(tf.cast(D,dtype = tf.float32)))

Standard Deviation is:  tf.Tensor(29.001303, shape=(), dtype=float32)
Variance is:  tf.Tensor(841.0756, shape=(), dtype=float32)


# Finding Positional Maximum and Minimum
* Returns the index of the max number

In [ ]:
tf.random.set_seed(10)
E = tf.random.uniform(shape=[50])
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.644151  , 0.8082472 , 0.8976548 , 0.6368902 , 0.6270969 ,
       0.9936013 , 0.02359486, 0.03668392, 0.5860578 , 0.5740315 ,
       0.09047401, 0.5755553 , 0.25272822, 0.11045039, 0.61225283,
       0.1290685 , 0.89660144, 0.06479812, 0.8622047 , 0.82242084,
       0.4016037 , 0.7659943 , 0.4539342 , 0.32376182, 0.4617684 ,
       0.32858098, 0.8104389 , 0.1609515 , 0.07981062, 0.5934839 ,
       0.6243702 , 0.9112947 , 0.88744843, 0.9568223 , 0.436625  ,
       0.9997524 , 0.24064243, 0.8281152 , 0.54077435, 0.8436167 ,
       0.33806038, 0.9431902 , 0.08632314, 0.68907607, 0.53072953,
       0.9125186 , 0.06304038, 0.95265174, 0.8152896 , 0.57640743],
      dtype=float32)>

In [ ]:
E[tf.argmax(E)],E[tf.argmin(E)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9997524>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.023594856>)

In [ ]:
tf.reduce_max(E) == E[tf.argmax(E)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# **Squeezing a tensor**
Removes all dimensions of value 1

In [ ]:
tf.random.set_seed(42)
F = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,50])
F

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
F_squeeze = tf.squeeze(F)
F_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# **One Hot Encoding Tensors**

In [ ]:
list = [1,2,3,0]
tf.one_hot(list, depth=4,on_value='Yess',off_value='No')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'No', b'Yess', b'No', b'No'],
       [b'No', b'No', b'Yess', b'No'],
       [b'No', b'No', b'No', b'Yess'],
       [b'Yess', b'No', b'No', b'No']], dtype=object)>

# **CPU an GPU connectivity**

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Tue Jun 11 05:02:18 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0              27W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
tf.__version__

'2.15.0'